xquery version "1.0-ml";

module namespace ql = "http://marklogic.com/community/components/queue/queue-log";

import module namespace qc = "http://marklogic.com/community/components/queue/queue-config" at "queue-config.xqy";
import module namespace qe = "http://marklogic.com/community/components/queue/queue-event" at "queue-event.xqy";


declare namespace queue = "http://marklogic.com/community/queue";

(:~ 
 : Functions to implement the 'ping' process. This process generates 
 : events in the database to be picked up during queue processing. 
 : These events generally don't have URIs associated with them. Instead
 : they cause events to be generated by the function handling the event
 :)

declare option xdmp:mapping "false";